[pytest]
addopts = --screenshot=only-on-failure --html=reports/report.html --self-contained-html
pythonpath = .
testpaths = tests
markers = 
    smoke: mark a test as a smoke test
    api: mark a test as an API test
    ui: mark a test as a UI test
bdd_features_base_dir = tests/bdd/features/